
-- Create pipe with auto_ingest enabled
CREATE OR REPLACE PIPE SALES_DB.RAW_SCHEMA.PIPE_ORDERS_AUTO
  AUTO_INGEST = TRUE
  AS
  COPY INTO SALES_DB.RAW_SCHEMA.ORDERS_RAW
  FROM @SALES_DB.RAW_SCHEMA.STG_S3_SALES_DB
  FILE_FORMAT = (
    TYPE = CSV 
    FIELD_DELIMITER = ',' 
    SKIP_HEADER = 1
  )
  ON_ERROR = 'CONTINUE';

SHOW PIPES LIKE 'PIPE_ORDERS_AUTO';

  -- Or describe to see details
DESC PIPE SALES_DB.RAW_SCHEMA.PIPE_ORDERS_AUTO;

SELECT SYSTEM$PIPE_STATUS('SALES_DB.RAW_SCHEMA.PIPE_ORDERS_AUTO');

-- View pipe execution history
SELECT *
FROM TABLE(SALES_DB.INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'RAW_SCHEMA.ORDERS_RAW',
    START_TIME => DATEADD(hours, -1, CURRENT_TIMESTAMP())
));

SELECT * FROM SALES_DB.RAW_SCHEMA.ORDERS_RAW;

-- Temporarily stop the pipe
ALTER PIPE SALES_DB.RAW_SCHEMA.PIPE_ORDERS_AUTO SET PIPE_EXECUTION_PAUSED = TRUE;

-- Delete the pipe
DROP PIPE SALES_DB.RAW_SCHEMA.PIPE_ORDERS_AUTO;